no idea

diff --git a/DockerFile b/DockerFile
--- a/DockerFile
+++ b/DockerFile
@@ -1,53 +1,122 @@
+# ##### DEPENDENCIES
+
+# FROM --platform=linux/amd64 node:16-alpine AS deps
+# RUN apk add --no-cache libc6-compat openssl1.1-compat
+# WORKDIR /app
+
+
+# COPY prisma ./
+# COPY package.json yarn.lock ./
+
+# RUN yarn --frozen-lockfile
+
+# ##### BUILDER
+# FROM --platform=linux/amd64 node:16-alpine AS builder
+# RUN apk add --no-cache libc6-compat openssl1.1-compat
+# WORKDIR /app
+
+# ENV DATABASE_URL postgresql://root:IokxLnuo9vltRPu1mrEVSjBL@esme.iran.liara.ir:30836/
+# ENV NEXTAUTH_SECRET 2497766051bc79ad394d017575fb3b13
+# ENV NEXTAUTH_URL https://gozarche.iran.liara.run
+# COPY --from=deps /app/node_modules ./node_modules
+# COPY prisma ./prisma/
+# COPY . .
+# RUN export NODE_ENV=production
+# RUN apk add --update --no-cache openssl1.1-compat
+# RUN yarn prisma generate
+# RUN yarn build
+
+
+# ##### RUNNER
+
+# FROM --platform=linux/amd64 node:16-alpine AS runner
+# WORKDIR /app
+
+# ARG DB
+
+# RUN printenv
+# ENV NODE_ENV production
+# ENV DATABASE_URL postgresql://root:IokxLnuo9vltRPu1mrEVSjBL@esme.iran.liara.ir:30836/
+# ENV NEXTAUTH_SECRET 2497766051bc79ad394d017575fb3b13
+# ENV NEXTAUTH_URL https://gozarche.iran.liara.run
+# ENV PORT 3000
+
+
+# COPY --from=builder /app/next.config.mjs ./
+# COPY --from=builder /app/public ./public
+# COPY --from=builder /app/package.json  /app/yarn.lock ./
+# COPY --from=builder /app/.next/standalone ./
+# COPY --from=builder /app/.next/static ./.next/static
+
+# EXPOSE 3000
+
+# CMD ["node", "server.js"]
 ##### DEPENDENCIES
 
 FROM --platform=linux/amd64 node:16-alpine AS deps
-RUN apk add --no-cache libc6-compat openssl
+RUN apk add --no-cache libc6-compat openssl1.1-compat
 WORKDIR /app
 
+# Install Prisma Client - remove if not using Prisma
 
 COPY prisma ./
-COPY package.json yarn.lock ./
 
-RUN yarn 
-RUN yarn prisma generate
+# Install dependencies based on the preferred package manager
+
+COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml\* ./
+
+ENV DATABASE_URL postgresql://root:St2cTJlo1pi7fYtDxzcFuzru@esme.iran.liara.ir:33721/postgres
+RUN \
+ if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+ elif [ -f package-lock.json ]; then npm ci; \
+ elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i; \
+ else echo "Lockfile not found." && exit 1; \
+ fi
+
 ##### BUILDER
 
-FROM node:16-alpine AS builder
-ENV DATABASE_URL postgresql://root:IokxLnuo9vltRPu1mrEVSjBL@esme.iran.liara.ir:30836/
+FROM --platform=linux/amd64 node:16-alpine AS builder
+WORKDIR /app
+
+ENV DATABASE_URL postgresql://root:St2cTJlo1pi7fYtDxzcFuzru@esme.iran.liara.ir:33721/postgres
 ENV NEXTAUTH_SECRET 2497766051bc79ad394d017575fb3b13
 ENV NEXTAUTH_URL https://gozarche.iran.liara.run
-WORKDIR /app
 COPY --from=deps /app/node_modules ./node_modules
-COPY prisma ./prisma/
 COPY . .
 
-RUN yarn prisma generate
-RUN yarn build
-
+# ENV NEXT_TELEMETRY_DISABLED 1
+RUN apk add --no-cache libc6-compat openssl1.1-compat
+RUN \
+ if [ -f yarn.lock ]; then SKIP_ENV_VALIDATION=1 yarn build; \
+ elif [ -f package-lock.json ]; then SKIP_ENV_VALIDATION=1 npm run build; \
+ elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && SKIP_ENV_VALIDATION=1 pnpm run build; \
+ else echo "Lockfile not found." && exit 1; \
+ fi
 
 ##### RUNNER
 
-FROM node:16-alpine AS runner
+FROM --platform=linux/amd64 node:16-alpine AS runner
 WORKDIR /app
-
-
-ARG DB
-
-ENV DS $DB
-RUN printenv
-ENV NODE_ENV production
-ENV DATABASE_URL postgresql://root:IokxLnuo9vltRPu1mrEVSjBL@esme.iran.liara.ir:30836/
+ENV DATABASE_URL postgresql://root:St2cTJlo1pi7fYtDxzcFuzru@esme.iran.liara.ir:33721/postgres
 ENV NEXTAUTH_SECRET 2497766051bc79ad394d017575fb3b13
 ENV NEXTAUTH_URL https://gozarche.iran.liara.run
-ENV PORT 3000
+ENV NODE_ENV production
+RUN apk add --no-cache libc6-compat openssl1.1-compat
 
+# ENV NEXT_TELEMETRY_DISABLED 1
+
+RUN addgroup --system --gid 1001 nodejs
+RUN adduser --system --uid 1001 nextjs
 
 COPY --from=builder /app/next.config.mjs ./
 COPY --from=builder /app/public ./public
-COPY --from=builder /app/package.json  /app/yarn.lock ./
-COPY --from=builder /app/.next/standalone ./
-COPY --from=builder /app/.next/static ./.next/static
+COPY --from=builder /app/package.json ./package.json
 
+COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
+COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
+
+USER nextjs
 EXPOSE 3000
+ENV PORT 3000
 
 CMD ["node", "server.js"]
